SELECT MAX(SALARY) FROM employees; 
SELECT MAX(SALARY) - MIN(SALARY) FROM employees; 

SELECT AVG(SALARY) AS "media_salario" FROM employees GROUP BY JOB_ID ORDER BY media_salario DESC;
SELECT SUM(SALARY) FROM employees;

SELECT ROUND(MAX(SALARY),2),ROUND(MIN(SALARY),2), ROUND(SUM(SALARY),2), ROUND(AVG(SALARY),2) FROM employees;

SELECT COUNT(JOB_ID) from employees GROUP BY JOB_ID HAVING JOB_ID = "IT_PROG";

SELECT JOB_ID, AVG(SALARY) media_salario FROM employees GROUP BY JOB_ID;

SELECT AVG(SALARY) media_salarial, COUNT(FIRST_NAME) number_emp FROM employees GROUP BY DEPARTMENT_ID HAVING number_emp >10;

UPDATE employees 
SET PHONE_NUMBER = REPLACE(PHONE_NUMBER,'515','777') WHERE PHONE_NUMBER LIKE '515%';

SELECT * FROM employees WHERE LENGTH(FIRST_NAME) >= 8;

SELECT EMPLOYEE_ID, FIRST_NAME, YEAR(HIRE_DATE) FROM employees;


SELECT EMPLOYEE_ID, FIRST_NAME, DAY(HIRE_DATE) FROM employees;


SELECT EMPLOYEE_ID, FIRST_NAME, MONTH(HIRE_DATE) FROM employees;

SELECT UCASE(FIRST_NAME) FROM employees;

SELECT LAST_NAME, HIRE_DATE FROM employees WHERE HIRE_DATE LIKE "1987-07%";


SELECT FIRST_NAME, LAST_NAME, DATEDIFF( CURRENT_DATE(), HIRE_DATE) FROM employees; 

SELECT * FROM employees;
